In [1]:
import pandas as pd

In [30]:
df11 = pd.read_csv("annual_aqi_by_county_2011.csv")
df12 = pd.read_csv("annual_aqi_by_county_2012.csv")
df13 = pd.read_csv("annual_aqi_by_county_2013.csv")
df14 = pd.read_csv("annual_aqi_by_county_2014.csv")
df15 = pd.read_csv("annual_aqi_by_county_2015.csv")

In [31]:
frames = [df11, df12, df13, df14, df15]
df = pd.concat(frames).reset_index()
df

,index,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,0,Alabama,Baldwin,2011,282,204,69,9,0,0,0,126,74,42,0,0,209,0,73,0
1,1,Alabama,Clay,2011,118,80,38,0,0,0,0,86,63,39,0,0,0,0,118,0
2,2,Alabama,Colbert,2011,279,214,64,1,0,0,0,101,61,42,0,0,197,0,82,0
3,3,Alabama,DeKalb,2011,336,257,78,1,0,0,0,101,63,40,0,0,271,0,65,0
4,4,Alabama,Elmore,2011,242,192,48,2,0,0,0,105,64,44,0,0,242,0,0,0
5,5,Alabama,Etowah,2011,275,208,67,0,0,0,0,99,62,41,0,0,188,0,87,0
6,6,Alabama,Houston,2011,283,207,76,0,0,0,0,100,67,44,0,0,207,0,76,0
7,7,Alabama,Jefferson,2011,365,118,208,33,6,0,0,182,105,58,2,0,120,3,224,16
8,8,Alabama,Lawrence,2011,95,70,25,0,0,0,0,82,59,34,0,0,0,0,95,0
9,9,Alabama,Madison,2011,331,222,105,4,0,0,0,126,77,44,0,0,202,0,76,53
10,10,Alabama,Mobile,2011,304,215,82,7,0,0,0,122,80,42,0,0,209,0,74,21
11,11,Alabama,Montgomery,2011,278,183,93,2,0,0,0,108,74,44,0,0,193,0,85,0
12,12,Alabama,Morgan,2011,280,193,85,2,0,0,0,115,74,43,0,0,203,0,77,0
13,13,Alabama,Russell,2011,278,172,104,2,0,0,0,126,71,46,0,0,183,0,95,0
14,14,Alabama,Shelby,2011,282,190,79,12,1,0,0,166,87,44,0,0,208,0,74,0
15,15,Alabama,Sumter,2011,198,174,24,0,0,0,0,93,54,38,0,0,198,0,0,0
16,16,Alabama,Talladega,2011,110,61,49,0,0,0,0,94,67,47,0,0,0,0,110,0
17,17,Alabama,Tuscaloosa,2011,279,234,44,1,0,0,0,103,56,38,0,0,184,0,95,0
18,18,Alabama,Walker,2011,107,70,37,0,0,0,0,84,65,43,0,0,0,0,107,0
19,19,Alaska,Aleutians East,2011,101,100,1,0,0,0,0,52,22,11,0,0,0,0,101,0
20,20,Alaska,Anchorage,2011,365,318,47,0,0,0,0,88,54,29,17,0,141,0,133,74
21,21,Alaska,Denali,2011,365,364,1,0,0,0,0,61,44,34,0,0,362,0,3,0
22,22,Alaska,Fairbanks North Star,2011,365,211,122,27,5,0,0,161,95,38,0,0,33,0,294,38
23,23,Alaska,Juneau,2011,353,299,54,0,0,0,0,88,57,23,0,0,0,0,344,9
24,24,Alaska,Kenai Peninsula,2011,166,166,0,0,0,0,0,36,18,8,0,0,0,0,166,0
25,25,Alaska,Matanuska-Susitna,2011,362,306,53,2,0,1,0,241,55,31,0,0,69,0,250,43
26,26,Alaska,Yukon-Koyukuk,2011,119,118,1,0,0,0,0,59,12,5,0,0,0,0,119,0
27,27,Arizona,Apache,2011,364,362,2,0,0,0,0,54,25,14,0,0,0,0,39,325
28,28,Arizona,Cochise,2011,352,215,126,11,0,0,0,119,80,47,0,0,322,0,17,13
29,29,Arizona,Coconino,2011,365,229,126,10,0,0,0,129,77,47,0,0,337,0,13,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5311,1031,Wisconsin,Oneida,2015,353,271,39,43,0,0,0,146,107,3,0,0,0,353,0,0
5312,1032,Wisconsin,Outagamie,2015,362,297,65,0,0,0,0,98,60,38,0,0,161,0,201,0
5313,1033,Wisconsin,Ozaukee,2015,365,299,61,5,0,0,0,122,60,36,0,0,187,0,178,0
5314,1034,Wisconsin,Racine,2015,185,154,30,1,0,0,0,105,67,39,0,0,185,0,0,0
5315,1035,Wisconsin,Rock,2015,192,165,27,0,0,0,0,100,58,41,0,0,192,0,0,0
5316,1036,Wisconsin,Sauk,2015,364,311,53,0,0,0,0,96,55,36,0,0,176,0,183,5
5317,1037,Wisconsin,Sheboygan,2015,198,154,33,10,1,0,0,159,80,40,0,0,198,0,0,0
5318,1038,Wisconsin,Taylor,2015,365,335,29,1,0,0,0,120,49,34,0,0,290,0,75,0
5319,1039,Wisconsin,Vilas,2015,204,188,16,0,0,0,0,84,48,33,0,0,173,0,31,0
5320,1040,Wisconsin,Walworth,2015,199,170,28,1,0,0,0,108,58,40,0,0,199,0,0,0
5321,1041,Wisconsin,Waukesha,2015,357,275,81,1,0,0,0,105,63,40,0,0,149,0,208,0
5322,1042,Wyoming,Albany,2015,365,279,86,0,0,0,0,93,60,45,0,0,314,0,7,44
5323,1043,Wyoming,Big Horn,2015,359,327,32,0,0,0,0,71,50,39,0,0,324,0,29,6
5324,1044,Wyoming,Campbell,2015,365,252,110,2,1,0,0,198,66,44,0,8,191,0,29,137
5325,1045,Wyoming,Carbon,2015,365,324,40,1,0,0,0,105,51,42,0,2,350,5,7,1
5326,1046,Wyoming,Converse,2015,365,293,67,3,2,0,0,161,58,43,0,0,284,0,18,63
5327,1047,Wyoming,Fremont,2015,365,288,77,0,0,0,0,97,58,45,0,0,337,0,28,0
5328,1048,Wyoming,Goshen,2015,167,152,13,2,0,0,0,138,49,23,0,0,10,0,157,0
5329,1049,Wyoming,Johnson,2015,57,56,1,0,0,0,0,56,18,6,0,0,0,0,57,0
5330,1050,Wyoming,Laramie,2015,365,308,56,0,1,0,0,152,61,42,1,3,327,1,29,4
5331,1051,Wyoming,Lincoln,2015,365,355,10,0,0,0,0,96,34,13,0,0,0,0,0,365
5332,1052,Wyoming,Natrona,2015,365,329,36,0,0,0,0,95,50,41,0,14,342,0,9,0
5333,1053,Wyoming,Park,2015,126,121,5,0,0,0,0,81,36,15,0,0,0,0,102,24
5334,1054,Wyoming,Platte,2015,60,57,3,0,0,0,0,86,46,14,0,0,0,0,0,60
5335,1055,Wyoming,Sheridan,2015,365,326,37,2,0,0,0,146,51,38,0,0,264,0,46,55
5336,1056,Wyoming,Sublette,2015,365,297,67,1,0,0,0,101,61,44,0,0,353,0,12,0
5337,1057,Wyoming,Sweetwater,2015,365,256,105,4,0,0,0,119,71,44,0,3,330,3,4,25
5338,1058,Wyoming,Teton,2015,365,325,39,1,0,0,0,107,51,42,0,0,353,0,9,3
5339,1059,Wyoming,Uinta,2015,365,316,47,2,0,0,0,101,54,41,0,0,354,0,0,11
5340,1060,Wyoming,Weston,2015,365,328,37,0,0,0,0,92,51,40,0,0,349,1,14,1

In [34]:
new_df = df.groupby(["County"]).mean()
new_df.head()

,index,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
County,,,,,,,,,,,,,,,,,,
Abbeville,822.400000,2013.000000,220.600000,205.600000,14.800000,0.200000,0.000000,0.0,0.0,92.400000,48.600000,36.200000,0.000000,0.0,220.600000,0.000000,0.000000,0.0
Ada,225.200000,2013.000000,365.200000,285.000000,72.000000,6.400000,1.600000,0.2,0.0,166.200000,65.000000,39.400000,4.800000,47.0,223.600000,0.200000,47.000000,42.6
Adair,722.000000,2013.000000,365.000000,227.400000,130.800000,6.400000,0.400000,0.0,0.0,137.600000,71.200000,45.600000,0.000000,1.6,212.600000,1.000000,147.000000,2.8
Adams,551.692308,2012.923077,341.192308,271.423077,66.730769,2.807692,0.230769,0.0,0.0,106.692308,57.307692,35.153846,0.192308,21.5,141.153846,3.653846,169.192308,5.5
Adjuntas,806.800000,2013.000000,63.400000,60.600000,2.800000,0.000000,0.000000,0.0,0.0,57.400000,33.800000,16.400000,0.000000,0.0,0.000000,0.000000,63.400000,0.0

In [35]:
new_df.to_csv("final_ap_df.csv")

In [42]:
# df_lung = pd.read_csv("lung_bycounty.csv")
df_skin = pd.read_csv("skin_bycounty.csv", encoding = 'ISO-8859-1')
# df_blood = pd.read_csv("leukemia_bycounty.csv")

In [45]:
df = df_skin

In [46]:
df_skin.head()

,County,FIPS,"Age-Adjusted Incidence Rate() - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend () in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,"US (SEER+NPCR)(1,10)",0,21.3,21.2,21.3,74467,rising,2.1,1.1,3
1,"Beaver County, Utah(7)",49001,79.6,50.9,118.5,5,*,*,*,*
2,"Summit County, Utah(7,8)",49043,76.1,63.0,91.0,29,rising,7.5,5.2,9.8
3,"Towns County, Georgia(7,8)",13281,62.1,43.8,86.3,11,rising,7,3.2,10.9
4,"Pickens County, Georgia(7,8)",13227,61.6,50.8,74.3,25,rising,7.8,3.3,12.5

In [29]:
frames2 = [df_lung, df_skin, df_blood]
df_cancer = pd.concat(frames2).reset_index()
df_cancer = df_cancer[df_cancer.line_race == "Data Suppressed"]
rate = df_cancer["CaseCount"].astype(dtype="float") / df_cancer["Population"].astype(dtype="float") * 100
rate

AttributeError: 'DataFrame' object has no attribute 'line_race'

In [20]:
new_df_cancer = df_cancer.groupby(["Year", "Area", "CancerType"]).mean()
new_df_cancer

                                                 index  AgeAdjustedRate   lci  \
Year Area                 CancerType
1999 Alabama              Leukemias                  3              9.3   8.4
                          Lung and Bronchus         19             72.8  70.4
                          Melanomas of the Skin     13             13.5  12.4
     Alaska               Leukemias                 35             15.4  11.2
                          Lung and Bronchus         20             79.2  69.4
                          Melanomas of the Skin      7             11.2   7.9
     Arizona              Leukemias                  5             10.6   9.7
                          Lung and Bronchus          4             59.7  57.6
                          Melanomas of the Skin     30             18.6  17.4
     Arkansas             Leukemias                 36              NaN   NaN
                          Lung and Bronchus         21              NaN   NaN
                          Melanomas of the Skin     42              NaN   NaN
     California           Leukemias                 11             12.3  11.9
                          Lung and Bronchus          8             61.0  60.1
                          Melanomas of the Skin     31             18.4  17.9
     Colorado             Leukemias                 22             13.9  12.7
                          Lung and Bronchus          1             51.6  49.3
                          Melanomas of the Skin     32             20.7  19.3
     Connecticut          Leukemias                 12             12.1  11.0
                          Lung and Bronchus          9             68.5  65.8
                          Melanomas of the Skin     43             21.4  19.9
     Delaware             Leukemias                  9             10.8   8.6
                          Lung and Bronchus         22             82.3  76.1
                          Melanomas of the Skin     14             13.3  10.8
     District of Columbia Leukemias                  1              8.5   6.2
                          Lung and Bronchus         23             76.0  68.9
                          Melanomas of the Skin      0              7.8   5.7
     Florida              Leukemias                 37             14.3  13.7
                          Lung and Bronchus         24             77.7  76.5
                          Melanomas of the Skin     33             17.5  16.9
...                                                ...              ...   ...
2016 South Dakota         Leukemias                914             16.9  14.3
                          Lung and Bronchus        894             58.2  53.6
                          Melanomas of the Skin    912             24.1  20.9
     Tennessee            Leukemias                883             12.1  11.3
                          Lung and Bronchus        916             70.9  69.1
                          Melanomas of the Skin    879             19.0  18.1
     Texas                Leukemias                899             12.9  12.5
                          Lung and Bronchus        882             48.5  47.7
                          Melanomas of the Skin    868             12.6  12.2
     Utah                 Leukemias                900             13.6  12.2
                          Lung and Bronchus        867             25.1  23.1
                          Melanomas of the Skin    913             41.2  38.8
     Vermont              Leukemias                869              9.0   7.0
                          Lung and Bronchus        910             60.5  55.3
                          Melanomas of the Skin    914             41.1  36.6
     Virginia             Leukemias                877             11.0  10.3
                          Lung and Bronchus        895             56.6  55.1
                          Melanomas of the Skin    880             19.2  18.4
     Washington           Leukemias                915             14.4  13.6
                          Lung and Bronchus        883             53.2  51.7
                          Melanomas of the Skin    915             25.5  24.3
     West Virginia        Leukemias                916             14.8  13.2
                          Lung and Bronchus        917             75.4  72.1
                          Melanomas of the Skin    916             22.1  20.1
     Wisconsin            Leukemias                917             15.7  14.7
                          Lung and Bronchus        896             58.3  56.5
                          Melanomas of the Skin    917             24.4  23.2
     Wyoming              Leukemias                884             12.2   9.7
                          Lung and Bronchus        875             44.7  39.8
                          Melanomas of the Skin    881             19.8  16.5

                                                  uci  Population
Year Area                 CancerType
1999 Alabama              Leukemias              10.3   4430141.0
                          Lung and Bronchus      75.4   4430141.0
                          Melanomas of the Skin  14.6   4430141.0
     Alaska               Leukemias              20.6    624779.0
                          Lung and Bronchus      89.8    624779.0
                          Melanomas of the Skin  15.2    624779.0
     Arizona              Leukemias              11.5   5023823.0
                          Lung and Bronchus      61.8   5023823.0
                          Melanomas of the Skin  19.8   5023823.0
     Arkansas             Leukemias               NaN         NaN
                          Lung and Bronchus       NaN         NaN
                          Melanomas of the Skin   NaN         NaN
     California           Leukemias              12.7  33499204.0
                          Lung and Bronchus      61.9  33499204.0
                          Melanomas of the Skin  18.9  33499204.0
     Colorado             Leukemias              15.2   4226018.0
                          Lung and Bronchus      54.1   4226018.0
                          Melanomas of the Skin  22.2   4226018.0
     Connecticut          Leukemias              13.3   3386401.0
                          Lung and Bronchus      71.2   3386401.0
                          Melanomas of the Skin  23.0   3386401.0
     Delaware             Leukemias              13.4    774990.0
                          Lung and Bronchus      88.9    774990.0
                          Melanomas of the Skin  16.1    774990.0
     District of Columbia Leukemias              11.3    570213.0
                          Lung and Bronchus      83.7    570213.0
                          Melanomas of the Skin  10.5    570213.0
     Florida              Leukemias              14.8  15759421.0
                          Lung and Bronchus      79.0  15759421.0
                          Melanomas of the Skin  18.1  15759421.0
...                                               ...         ...
2016 South Dakota         Leukemias              19.7    861542.0
                          Lung and Bronchus      63.1    861542.0
                          Melanomas of the Skin  27.6    861542.0
     Tennessee            Leukemias              12.9   6649404.0
                          Lung and Bronchus      72.8   6649404.0
                          Melanomas of the Skin  20.1   6649404.0
     Texas                Leukemias              13.4  27904862.0
                          Lung and Bronchus      49.4  27904862.0
                          Melanomas of the Skin  13.0  27904862.0
     Utah                 Leukemias              15.0   3044321.0
                          Lung and Bronchus      27.1   3044321.0
                          Melanomas of the Skin  43.8   3044321.0
     Vermont              Leukemias              11.5    623354.0
                          Lung and Bronchus      66.1    623354.0
                          Melanomas of the Skin  46.1    623354.0
     Virginia             Leukemias              11.7   8414380.0
                          Lung and Bronchus      58.2   8414380.0
                          Melanomas of the Skin  20.2   8414380.0
     Washington           Leukemias              15.3   7280934.0
                          Lung and Bronchus      54.9   7280934.0
                          Melanomas of the Skin  26.6   7280934.0
     West Virginia        Leukemias              16.5   1828637.0
                          Lung and Bronchus      78.9   1828637.0
                          Melanomas of the Skin  24.1   1828637.0
     Wisconsin            Leukemias              16.7   5772917.0
                          Lung and Bronchus      60.1   5772917.0
                          Melanomas of the Skin  25.6   5772917.0
     Wyoming              Leukemias              15.2    584910.0
                          Lung and Bronchus      50.2    584910.0
                          Melanomas of the Skin  23.6    584910.0

[2754 rows x 5 columns]